FROM python:3.12

LABEL maintainer="M/hamid"

WORKDIR /code

RUN apt-get update && apt-get install -y \
    build-essential \
    protobuf-compiler \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip install poetry

COPY ./pyproject.toml /code/ 

RUN poetry config virtualenvs.create false

RUN poetry install 

COPY . /code/

EXPOSE 8084

CMD ["poetry", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0","--port", "8084", "--reload"]
